# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Useful Scripts
email: hschmale16@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hschmale16.github.io/UsefulScripts"
twitter_username: jekyllrb
github_username:  HSchmale16

# Build settings
markdown: kramdown
